name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0' 

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./giphy_frontend

    - name: Run tests
      run: flutter test
      working-directory: ./giphy_frontend

    - name: Build APK
      run: flutter build apk
      working-directory: ./giphy_frontend